const translations = {
    id: {
        selamatDatang:
          "Selamat datang di Senergy Kos Gang Saleh, solusi cerdas untuk pengelolaan energi yang efisien dan berkelanjutan. Kami membantu penghuni kos memantau dan mengontrol penggunaan listrik secara real-time, sehingga dapat menghemat biaya dan berkontribusi pada lingkungan yang lebih baik.",
        masuk: "Masuk",
        daftar: "Daftar",
        halamanLupaPassword: "Lupa Password",
        lupaKataSandi: "Lupa kata sandi?",
        ubahKataSandi: "Ubah Kata Sandi", 
        kataSandiBaru: "Kata Sandi Baru",
        konfirmasiKataSandiBaru: "Konfirmasi Kata Sandi Baru",
        placeholderKataSandiBaru: "Masukkan kata sandi baru Anda",
        placeholderKonfirmasiKataSandiBaru: "Masukkan kata sandi baru Anda",
        nomorTelahDigunakan: "Nomor telah digunakan",
        emailTidakDitemukan: "Email yang Anda masukkan tidak ditemukan",
        kataSandiBerhasilDiubah: "Kata sandi berhasil diubah!",
        kataSandiTidakSesuai: "Kata sandi tidak sesuai",
        kataSandiGagalDiubah: "Terjadi kesalahan saat mengubah kata sandi",
        kataSandiSamaSebelumnya: "Kata sandi telah digunakan",
        harian: "Harian",
        filterHarianStandar: "Harian Bawaan",
        filterHarianKalender: "Kalender",
        bulanan: "Bulanan",
        filterBulananSemua: "Semua Bulan",
        filterBulananRentang: "Rentang Bulan",
        tahun: "Tahun",
        dari: "Dari",
        sampai: "Sampai",
        keteranganFilter: "Keterangan",
        nomorTelepon: "Nomor Telepon",
        namaLengkap: "Nama Lengkap",
        email: "Email",
        kataSandi: "Kata Sandi",
        belumPunyaAkun: "Belum punya akun?",
        sudahPunyaAkun: "Sudah punya akun?",
        sudahIngatKataSandi: "Sudah ingat kata sandi?",
        daftarDisini: "Daftar disini",
        masukDisini: "Masuk disini",
        placeholderEmail: "Masukkan email Anda",
        placeholderKataSandi: "Masukkan kata sandi Anda",
        placeholderNamalengkap: "Masukkan nama lengkap Anda",
        placeholderNomorTelepon: "Masukkan nomor telepon Anda",
        masukBerhasil: "Masuk berhasil!",
        emailGagal: "Email yang Anda masukkan salah",
        katasandiGagal: "Kata sandi yang Anda masukkan salah",
        terjadiKesalahan: "Terjadi kesalahan saat masuk",
        daftarBerhasil: "Daftar berhasil!",
        emailTelahDigunakan: "Email telah digunakan",
        daftarTerjadiKesalahan: "Terjadi kesalahan saat daftar",
        domainEmail: "Email harus mengandung @ dan domain (contoh: user@gmail.com)",
        simbolEmail: "Email harus mengandung simbol @",
        satuSimbolEmail: "Email hanya boleh mengandung satu simbol @",
        domainTitikEmail: "Email harus mengandung domain dengan titik (contoh: gmail.com)",
        awalAkhirEmail: "Email tidak boleh diawali atau diakhiri dengan @",
        titikGandaEmail: "Email tidak boleh mengandung titik berturut-turut",
        tidakSpasiEmail: "Email tidak boleh mengandung spasi",
        formatTidakValidEmail: "Format email tidak valid, mohon cek penulisan Anda",
        formatValidEmail: "Email Valid",
        passwordMinimal8: "Password minimal 8 karakter",
        passwordTidakSpasi: "Password tidak boleh dimulai atau diakhiri dengan spasi",
        passwordTidakUmum: "Password terlalu umum, gunakan kombinasi yang lebih unik",
        passwordSamaEmail: "Password tidak boleh sama dengan email",
        passwordKombinasi: "Minimal 3 jenis karakter (huruf besar, huruf kecil, angka, simbol)",
        passwordTidakValid: "Password tidak valid",
        passwordValid: "Password Valid",
        passwordLemah: "Lemah",
        passwordSedang: "Sedang",
        passwordKuat: "Kuat",
        passwordSangatKuat: "Sangat Kuat",
        berandaKontak: "Kontak",
        berandaBeranda: "Beranda",
        berandaAkun: "Akun",
        berandaKamar: "Kamar",
        berandaKontrol: "Kontrol",
        berandaGrafik: "Grafik",
        berandaSelamatDatang: "Selamat Datang di Senergy",
        berandaDeskripsi: "Pemantauan dan Kontrol Penggunaan Listrik di Kos Gang Saleh",
        berandaFiturUtama: "Fitur Utama",
        berandaJudulGrafik: "Grafik",
        berandaDeskripsiGrafik: "Grafik ini digunakan untuk pemantauan terhadap penggunaan energi secara real-time. Dengan fitur ini, Pengguna dapat melihat banyaknya listrik yang digunakan setiap saat, memungkinkan pengguna untuk membuat keputusan yang lebih baik dan menghindari pemborosan.",
        berandaJudulKontrol: "Kontrol",
        berandaDeskripsiKontrol: "Atur batas penggunaan listrik sesuai kebutuhan. Dengan fitur ini, Pengguna dapat menetapkan batasan penggunaan listrik untuk setiap kamar, sehingga membantu pengguna mengontrol pengeluaran dan memastikan penggunaan energi yang efisien.",
        berandaJudulNotifikasi: "Notifikasi",
        berandaDeskripsiNotifikasi: "Fitur digunakan untuk mendapatkan notifikasi langsung saat penggunaan listrik mendekati batas yang pengguna tetapkan. Fitur ini memastikan pengguna selalu mendapatkan informasi dan dapat mengambil tindakan yang diperlukan untuk menghindari pemborosan dan pengeluaran yang berlebihan.",
        berandaHakCipta: "2025 Senergy. Hak cipta dilindungi undang-undang.",
        ubahDataUser: "Ubah",
        keluarDataUser: "Keluar",
        hapusDataUser: "Hapus Akun",
        keluarBerhasil: "Keluar berhasil!",
        dataBerhasilDiubah: "Data berhasil diubah!",
        gagalUbahData: "Gagal mengubah data",
        berhasilHapusAkun: "Hapus akun berhasil!",
        gagalHapusAkun: "Email tidak sesuai",
        errorHapusAkun: "Terjadi kesalahan saat hapus akun",
        hapusAkun: "Apakah Anda yakin ingin menghapus akun ini?",
        ya: "Ya",
        tidak: "Tidak",
        konfirmasiHapus: "Konfirmasi",
        batalHapus: "Batal",
        judulHalamanKontak: "Kontak Kami Jika Mengalami Kendala",
        labelPesanAnda: "Pesan Anda",
        placeholderPesan: "Masukkan pesan Anda",
        pesanKirim: "Kirim",
        emailTidakSesuai: "Email yang anda masukkan tidak valid",
        pesanBerhasilTerkirim: "Pesan berhasil dikirim",
        pesanGagalTerkirim: "Gagal mengirimkan pesan",
        errorKirimPesan: "Terjadi kesalahan saat mengirim pesan",
        hasilLaporan: "Laporan Penggunaan Listrik",
        pilihanMcb: "Pilih MCB",
        keterangan: "Keterangan", 
        modeGrafik: "Data Grafik",
        harian: "Harian",
        terbaru: "Terbaru",
        filterDariTanggal: "Dari",
        filterSampaiTanggal: "Sampai",
        tombolHariIni: "Hari ini",
        tombol7Hari: "7 Hari Terakhir",
        tombol30Hari: "30 Hari Terakhir",
        tombol1Jam: "1 Jam Terakhir",
        tombol6Jam:"6 Jam Terakhir",
        tombol12Jam:"12 Jam Terakhir",
        tombolGrafikTerkini:"Tampilkan grafik terbaru",
        kamar: "Kamar",
        kamar1: "Kamar 1",
        kamar2: "Kamar 2",
        kamar3: "Kamar 3",
        kamar4: "Kamar 4",
        kamar5: "Kamar 5",
        kamar6: "Kamar 6",
        kamar7: "Kamar 7",
        kamar8: "Kamar 8",
        kamar9: "Kamar 9",
        kamar10: "Kamar 10",
        kamar11: "Kamar 11",
        kamar12: "Kamar 12",
        dayGrafik: {
            Senin: "Senin",
            Selasa: "Selasa",
            Rabu: "Rabu",
            Kamis: "Kamis",
            Jumat: "Jumat",
            Sabtu: "Sabtu",
            Minggu: "Minggu"
        },
        monthGrafik: {
            Januari: "Januari",
            Februari: "Februari",
            Maret: "Maret",
            April: "April",
            Mei: "Mei",
            Juni: "Juni",
            Juli: "Juli",
            Agustus: "Agustus",
            September: "September",
            Oktober: "Oktober",
            November: "November",
            Desember: "Desember"
        },
        totalKonsumsi: "Ringkasan Total Konsumsi",
        periodePenggunaan: "Periode",
        day: "hari",
        jumlahPenggunaanPerMcb: "Total Keseluruhan",
        kamarKos: "Kamar",
        sisa: "Sisa",
        hariPenggunakos: "Hari",
        editPenggunaan: "Penggunaan",
        batasKwhKamar: "Batas",
        awalDaftarKamar: "Tanggal Daftar",
        tombolOnKontrol: "Nyala",
        tombolOffKontrol: "Mati",
        kamarSedangDigunakan: "Sedang digunakan",
        gunakanKamar: "Gunakan Kamar",
        namaDanNomorWajibKamar: "Nama lengkap dan nomor telepon wajib diisi!",
        labelBatasKwh: "Batas kWh",
        placeholderBatasKwh: "Masukkan batas kWh",
        labelSisaHari: "Sisa Hari",
        placeholderSisaHari: "Masukkan sisa hari",
        berhasilDaftarKamar: "Pendaftaran kamar berhasil!",
        gagalDaftarKamar: "Pendaftaran kamar gagal!",
        tutupDaftarKamar: "Tutup",
        catatanDaftarKamar: "*Catatan: Perhatikan kembali nama lengkap Anda dan nomor telepon Anda yang aktif.",
        editJudul: "Edit Data Penghuni",
        editTombolKamar: "Edit",
        labelTambahanKwh: "Tambahan kWh",
        placeholderTambahanKwh : "Masukkan tambahan kWh",
        konfirmasiTambahKwh1: "Anda akan menambah",
        konfirmasiTambahKwh2: "kWh dengan estimasi biaya",
        konfirmasiTambahKwh3: "Lanjutkan?",
        editBiayaTambahan: "Estimasi Biaya",
        editKwhTidakNegatif: "Tambahan kWh tidak boleh negatif",
        editTombolPerbarui: "Perbarui Data",
        berhasilEditKamar: "Data kamar berhasil diubah!",
        editInfo: "*Catatan: Pastikan data yang dimasukkan sudah benar sebelum menyimpan perubahan.",
        hapusTombolKamar: "Hapus",
        konfirmasiHapusKamar: "Apakah Anda yakin ingin menghapus penghuni dari kamar",
        berhasilHapusKamar: "Penghuni berhasil dihapus dan kamar dikosongkan!",
        gagalHapusKamar: "Hapus kamar gagal!",
        tombolPembatalan: "Batal",
        infoAman: "Aman",
        infoPeringatan: "Peringatan",
        infoMelebihi: "Melebihi Batas",
        peringatanKwh: "hampir melebihi batas penggunaan listrik!",
        melebihiKwh: "telah melebihi batas penggunaan listrik!",
        emailAtauPasswordSalah: "Email atau password yang Anda masukkan salah",
        masalahJaringan: "Masalah jaringan, periksa koneksi internet Anda",
        nomorTeleponAngka: "Nomor telepon hanya boleh berisi angka",
        nomorTeleponPanjang: "Nomor telepon harus 9-13 digit",
        nomorTeleponFormat: "Nomor telepon harus dimulai dengan 8 (tanpa +62 dan 0)",
        nomorTeleponValid: "Nomor telepon valid",
        mohonLengkapiForm: "Mohon lengkapi semua field dengan benar",
        emailTidakTerdaftar: "Email tidak terdaftar di sistem kami",
        emailKirimBerhasil: "Tautan reset kata sandi telah dikirim ke email Anda",
        emailTidakDitemukan: "Email tidak ditemukan di Firebase Authentication",
        emailGagalKirim: "Gagal mengirim tautan reset kata sandi",
        relayKamar: "Relay kamar",
        dinonaktifkanKamar: "dinonaktifkan karena melebihi batas penggunaan listrik",
        gagalMemuatKamar: "Gagal memuat data kamar. Silakan coba lagi.",
        gagalUpdateKamar: "Gagal mengupdate data. Silakan coba lagi.",
        namaPenggunaKos: "Nama",
        nomorPenggunaKos: "Nomor",
        cobaLagi: "Coba lagi",
        tidakAdaNotifikasiOverlimit: "Tidak ada kamar yang melebihi batas",
        hapusNotifikasi: "Hapus",
        tanggalNotifikasi: "Tanggal",
        pendaftaranKamar: "Pendaftaran Kamar",
        mengirim:"Mengirim...",
        pendaftaranTidakTersedia: "Pendaftaran Tidak Tersedia",
        kembaliKeLogin: "Kembali ke halaman masuk",
        gagalAmbilData: "Gagal dalam pengambilan data user",
        userTidakAda: "Pengguna tidak ditemukan",
        passwordTidakBolehKosong: "Password tidak boleh kosong",
        tampilanSetelahDelete: "Anda telah keluar",
        passwordSalah: "Password salah",
        perluLoginUlang: "Silakan masuk kembali",
        verifikasiEmailBaru: "Link verifikasi telah dikirim ke email baru. Silakan verifikasi untuk menyelesaikan perubahan",
        password: "Kata Sandi",
    },
    en: {
        selamatDatang:
            "Welcome to Senergy Kos Gang Saleh, a smart solution for efficient and sustainable energy management. We help boarding house residents monitor and control electricity usage in real-time, so they can save money and contribute to a better environment.",
        masuk: "Sign In",
        daftar: "Sign Up",
        halamanLupaPassword: "Forgot Password",
        lupaKataSandi: "Forgot password?",
        ubahKataSandi: "Change Password",
        kataSandiBaru: "New Password",
        konfirmasiKataSandiBaru: "Confirm New Password",
        placeholderKataSandiBaru: "Enter your new password",
        placeholderKonfirmasiKataSandiBaru: "Enter your new password",
        nomorTelahDigunakan: "Number has been used",
        emailTidakDitemukan: "The email you entered was not found",
        kataSandiBerhasilDiubah: "Password changed successfully!",
        kataSandiTidakSesuai: "Password does not match",
        kataSandiGagalDiubah: "An error occurred while changing the password",
        kataSandiSamaSebelumnya: "Password has been used",
        harian: "Daily",
        filterHarianStandar: "Default Daily",
        filterHarianKalender: "Calendar",
        bulanan: "Monthly",
        filterBulananSemua: "All Months",
        filterBulananRentang: "Range of Months",
        tahun: "Year",
        dari: "From",
        sampai: "Until",
        keteranganFilter: "Description",
        nomorTelepon: "Phone Number",
        namaLengkap: "Full Name",
        email: "Email",
        kataSandi: "Password",
        belumPunyaAkun: "Don't have an account yet?",
        sudahPunyaAkun: "Already have an account?",
        sudahIngatKataSandi: "Remember your password?",
        daftarDisini: "Register here",
        masukDisini: "Sign in here",                       
        placeholderEmail: "Enter your email",
        placeholderKataSandi: "Enter your password",
        placeholderNamalengkap: "Enter your full name",
        placeholderNomorTelepon: "Enter your phone number",
        masukBerhasil: "Login successful!",
        emailGagal: "The email you entered is incorrect",
        katasandiGagal: "The password you entered is incorrect",
        terjadiKesalahan: "An error occurred while logging in",
        daftarBerhasil: "Register successful!",
        emailTelahDigunakan: "Email has been used",
        daftarTerjadiKesalahan: "An error occurred while registering",
        domainEmail: "Email must contain @ and domain (example: user@gmail.com)",
        simbolEmail: "Email must contain the @ symbol",
        satuSimbolEmail: "Emails can only contain one @ symbol",
        domainTitikEmail: "Email must contain domain with dot (example: gmail.com)",
        awalAkhirEmail: "Email cannot start or end with @",
        titikGandaEmail: "Email cannot contain consecutive dots",
        tidakSpasiEmail: "Email cannot contain spaces",
        formatTidakValidEmail: "Invalid email format, please check your writing",
        formatValidEmail: "Valid email",
        passwordMinimal8: "Password minimum 8 characters",
        passwordTidakSpasi: "Passwords cannot start or end with a space",
        passwordTidakUmum: "Password is too common, use a more unique combination",
        passwordSamaEmail: "Password cannot be the same as email",
        passwordKombinasi: "Minimum 3 types of characters (uppercase, lowercase, numbers, symbols)",
        passwordTidakValid: "Invalid password",
        passwordValid: "Valid Password",
        passwordLemah: "Weak",
        passwordSedang: "Moderate",
        passwordKuat: "Strong",
        passwordSangatKuat: "Very Strong", 
        berandaKontak: "Contact",
        berandaBeranda: "Home",
        berandaAkun: "Account",
        berandaKamar: "Room",
        berandaKontrol: "Control",
        berandaGrafik: "Graph",
        berandaSelamatDatang: "Welcome to Senergy",
        berandaDeskripsi: "Monitoring and Control of Electricity Usage at Kos Gang Saleh",
        berandaFiturUtama: "Main Features",
        berandaJudulGrafik: "Graph",
        berandaDeskripsiGrafik: "This graph is used for real-time monitoring of energy usage. With this feature, Users can see how much electricity is being used at any given time, allowing users to make better decisions and avoid waste.",
        berandaJudulKontrol: "Control",
        berandaDeskripsiKontrol: "Set electricity usage limits as needed. With this feature, users can set electricity usage limits for each room, helping users control spending and ensure efficient energy use.",
        berandaJudulNotifikasi: "Notification",
        berandaDeskripsiNotifikasi: "The feature is used to get immediate notification when electricity usage approaches the limit set by the user. This feature ensures that users are always informed and can take necessary actions to avoid waste and excessive spending.",
        berandaHakCipta: "2025 Senergy. All rights reserved.",
        ubahDataUser: "Change",
        keluarDataUser: "Log Out",
        hapusDataUser: "Delete Account",
        keluarBerhasil: "Logout successful!",
        dataBerhasilDiubah: "Data successfully changed!",
        gagalUbahData: "Failed to change data",
        berhasilHapusAkun: "Delete account successful!",
        gagalHapusAkun: "Email does not match",
        errorHapusAkun: "An error occurred while deleting the account",
        hapusAkun: "Are you sure you want to delete this account?",
        ya: "Yes",
        tidak: "No",
        konfirmasiHapus: "Confirm",
        batalHapus: "Cancel",
        judulHalamanKontak: "Contact Us If You Have Problems",
        labelPesanAnda: "Your Message",
        placeholderPesan: "Enter your message",
        pesanKirim: "Send",
        emailTidakSesuai: "The email you entered is invalid",
        pesanBerhasilTerkirim: "Message sent successfully",
        pesanGagalTerkirim: "Failed to sent message",
        errorKirimPesan: "An error occurred while sending the message",
        hasilLaporan: "Elictricity Usage Report",
        pilihanMcb: "Select MCB",
        keterangan: "Information", 
        modeGrafik: "Graphic Data",
        harian: "Daily",
        terbaru: "Latest",
        filterDariTanggal: "From",
        filterSampaiTanggal: "Until",
        tombolHariIni: "Today",
        tombol7Hari: "Last 7 Days",
        tombol30Hari: "Last 30 Days",
        tombol1Jam: "Last 1 Hour",
        tombol6Jam:"Last 6 Hour",
        tombol12Jam:"Last 12 Hour",
        tombolGrafikTerkini:"Show the latest charts",
        kamar: "Room",
        kamar1: "Room 1",
        kamar2: "Room 2",
        kamar3: "Room 3",
        kamar4: "Room 4",
        kamar5: "Room 5",
        kamar6: "Room 6",
        kamar7: "Room 7",
        kamar8: "Room 8",
        kamar9: "Room 9",
        kamar10: "Room 10",
        kamar11: "Room 11",
        kamar12: "Room 12",
        dayGrafik: {
            Senin: "Monday",
            Selasa: "Tuesday",
            Rabu: "Wednesdey",
            Kamis: "Thursday",
            Jumat: "Friday",
            Sabtu: "Saturday",
            Minggu: "Sunday"
        },
        monthGrafik: {
            Januari: "January",
            Februari: "February",
            Maret: "March",
            April: "April",
            Mei: "May",
            Juni: "June",
            Juli: "July",
            Agustus: "August",
            September: "September",
            Oktober: "October",
            November: "November",
            Desember: "December"
        },
        totalKonsumsi: "Total Consumption Summary",
        periodePenggunaan: "Period",
        day: "day",
        jumlahPenggunaanPerMcb: "Total Overall",
        kamarKos: "Room",
        sisa: "Remainder",
        hariPenggunakos: "Day",
        editPenggunaan: "Use",
        batasKwhKamar: "Limit",
        awalDaftarKamar: "Registration Date",
        tombolOnKontrol: "ON",
        tombolOffKontrol: "OFF",
        kamarSedangDigunakan: "In use",
        gunakanKamar: "Use Room",
        namaDanNomorWajibKamar: "Full name and phone number are required!",
        labelBatasKwh: "kWh Limit",
        placeholderBatasKwh: "Enter kWh limit",
        labelSisaHari: "Remaining Day",
        placeholderSisaHari: "Enter remaining day",
        berhasilDaftarKamar: "Room registration successful!",
        gagalDaftarKamar: "Room registration failed!",
        tutupDaftarKamar: "Close",
        catatanDaftarKamar: "*Note: Please double check your full name and your active phone number.",
        editJudul: "Edit Resident Data",
        editTombolKamar: "Edit",
        labelTambahanKwh: "Additional kWh",
        placeholderTambahanKwh : "Enter additional kWh",
        konfirmasiTambahKwh1: "You will add",
        konfirmasiTambahKwh2: "kWh at an estimated cost of",
        konfirmasiTambahKwh3: "Continue?",
        editBiayaTambahan: "Estimated Costs",
        editKwhTidakNegatif: "Additional kWh cannot be negative",
        editTombolPerbarui: "Update Data",
        berhasilEditKamar: "Room data successfully changed!",
        editInfo: "*Note: Make sure the data entered is correct before saving changes.",
        hapusTombolKamar: "Delete",
        konfirmasiHapusKamar: "Are you sure you want to remove the occupant from the room",
        berhasilHapusKamar: "Occupant successfully removed and room vacated!",
        gagalHapusKamar: "Delete room failed!",
        tombolPembatalan: "Cancel",
        infoAman: "Safe",
        infoPeringatan: "Warning",
        infoMelebihi: "Overlimit",
        peringatanKwh: "almost exceeded the electricity usage limit!",
        melebihiKwh: "has exceeded the electricity usage limit!",
        emailAtauPasswordSalah: "The email or password you entered is incorrect",
        masalahJaringan: "Network problem, check your internet connection",
        nomorTeleponAngka: "Phone number may only contain digits",
        nomorTeleponPanjang: "Phone number must be 9-13 digits long",
        nomorTeleponFormat: "Phone number must start with 8 (without +62 and 0)",
        nomorTeleponValid: "Valid phone number",
        mohonLengkapiForm: "Please complete all fields correctly",
        emailTidakTerdaftar: "Email is not registered in our system",
        emailKirimBerhasil: "A password reset link has been sent to your email",
        emailGagalKirim: "Failed to send password reset link",
        relayKamar: "Room relay",
        dinonaktifkanKamar: "disabled due to exceeding the electricity usage limit",
        gagalMemuatKamar: "Failed to load room data. Please try again.",
        gagalUpdateKamar: "Failed to update data. Please try again.",
        namaPenggunaKos: "Name",
        nomorPenggunaKos: "Number",
        cobaLagi: "Try again",
        tidakAdaNotifikasiOverlimit: "There are no overlimit rooms",
        hapusNotifikasi: "Delete",
        tanggalNotifikasi: "Date",
        pendaftaranKamar: "Room Registration",
        mengirim:"Sending...",
        pendaftaranTidakTersedia: "Registration Not Available",
        kembaliKeLogin: "Return to login page",
        gagalAmbilData: "Failed to retrieve user data",
        userTidakAda: "User not found",
        passwordTidakBolehKosong: "Password cannot be empty",
        tampilanSetelahDelete: "You have logged out",
        passwordSalah: "Incorrect password",
        perluLoginUlang: "Please log in again",
        verifikasiEmailBaru: "A verification link has been sent to the new email. Please verify it to complete the change",
        password: "Password",
    }
};

export default translations;